### ISSUE TITLE
Feature request: add support for ATT&CK Version 14

### ISSUE THREAD

**Issue by RobbeVandenDaele** [rabobank-cdc/DeTTECT#107]
Hi,

ATT&CK version 14 was recently announced https://medium.com/mitre-attack/attack-v14-fa473603f86b. Is there a plan to support the V14 techniques in the future?

Thanks in advance and looking forward to it.

**Comment by rubinatorz** [comment]
Hi @RobbeVandenDaele 

Yes! As of today. Enjoy!

_(You might need to reload the DeTT&CT Editor in your browser the hard way to load the assets online instead of your local browser cache. And you might need to clean your DeTTECT/cache folder to get the latest ATT&CK version data.)_

**Comment by RobbeVandenDaele** [comment]
Thank you @rubinatorz for the quick response and implementation!
