### ISSUE TITLE
Duplicate value for applicable_to

### ISSUE THREAD

**Issue by RobbeVandenDaele** [rabobank-cdc/DeTTECT#109]
Hi, 

I have a techniques file with a lot of detections related to certain data sources per technique. When I try to upload the file in the DeTT&CT Editor I get errors saying "A duplicate value for 'applicable_to' was found within the detection section if technique <technique>: '<character>'"
<img width="937" alt="image" src="https://github.com/rabobank-cdc/DeTTECT/assets/107618465/e7b478a6-f1a0-4871-979e-d8b248234775">

When checking the file, I do not find any duplicate value for the 'applicable_to' property within one technique. I also see that the 'applicable_to' field that is being shown in the error is not the real 'applicable_to' field but only the first character:
<img width="270" alt="image" src="https://github.com/rabobank-cdc/DeTTECT/assets/107618465/bce7bb20-f450-469d-a6d6-8eee83b56d10">
<img width="368" alt="image" src="https://github.com/rabobank-cdc/DeTTECT/assets/107618465/c936cd59-31b3-4d1d-865e-7ca041078091">

Can it be that this is a bug in the editor? Or is my techniques file really not correct? I will drop my techniques file so the issue can be reproduced. 
[techniques_new.txt](https://github.com/rabobank-cdc/DeTTECT/files/13312899/techniques_new.txt)

Thank you in advance. 
Kind regards
Robbe

**Comment by rubinatorz** [comment]
Hi @RobbeVandenDaele 

The applicable_to value should be a list. So if you convert for example:

`- applicable_to: WAF`

to

`- applicable_to: [WAF]`

And do that for all items, then it should work.

The Editor is quite strict in this. The CLI python tool is more tolerant, but will give a warning:

`[!] The below YAML file contains possible errors. It's recommended to check via the '--health' argument.`

And if you do a health check, you'll see:

`[!] Technique ID: T1190 the key-value pair 'applicable_to' in 'detection' is NOT a list`
