### ISSUE TITLE
question about the techniques administration file

### ISSUE THREAD

**Issue by sri-telstra** [rabobank-cdc/DeTTECT#11]
Hi Marcus,

I noticed you have put out new features in your latest drop which is fantastic, havent yet had the chance to explore the docker instance but will do in the coming days. Many thanks.

I have had this nagging thing which I thought I should ask. I found that when we use the command 
python3 dettect.py ds -f sample-data/data-sources-endpoints.yaml -y
to generate the techniques-administration file, it gets written to the output folder but it is not the same file that is used in the following command to obtain the detections map. In fact there are close to 300 lines in difference. There is also some formatting difference in the way the fields are populated in the two files.

I understand that was an example, but when I used the other file, it turned out a blank detections map. In fact I also noticed you have mentioned that detections and visibility need not be connected. What am I missing in that connection? I am trying to understand what it would take if I were to map the same my linux fleet and use the detections map using the thence generated techniques-administration file.

Is there any assumption underpinning this mode of execution? 

Kind regards
Sri

**Comment by marcusbakker** [comment]
Hi Sriram,

We have put a short [instruction](https://github.com/rabobank-cdc/DeTTECT/wiki/Installation-and-requirements#docker) on the Wiki on how to get started with the docker instance :-).

When you refer to "the detection map", you are referring to this [picture](https://raw.githubusercontent.com/wiki/rabobank-cdc/DeTTECT/images/example_detection.png)? The command `python3 dettect.py ds -f sample-data/data-sources-endpoints.yaml -y` will provide you with a YAML technique administration file. In this file, detections are left blank. Only visibility is filled in based on your data sources (`data-sources-endpoints.yaml`). The result is YAML file with a rough overview of your [visibility coverage](https://github.com/rabobank-cdc/DeTTECT/wiki/Getting-started#score-visibility). In the file `techniques-administration-endpoints.yaml` we choose the manually score the visibility of some of the techniques. If I understand you correctly, that will explain the difference in the score of the visibility.

Regarding the relation between visibility and detection. These are two separate things. Visibility tells you something about what you could potentially detect. When you want to use DeTT&CT for your Linux fleet it can be a good idea to:
* start with creating a data source administration file
* use that file to draft a tech. admin. YAML file
* the visibility scores within this file a rough estimation
* manually start scoring your detection per technique in this tech. admin. YAML file
* where it makes sense or where it is of value, you can then manually score the visibility of a technique. There can be multiple reasons why this is necessary. See: [Score visibility](https://github.com/rabobank-cdc/DeTTECT/wiki/Getting-started#score-visibility).

Does the above answer your questions and helps you to get started?

Regards,
Marcus

**Comment by sri-telstra** [comment]
Thanks Marcus, I think I see your perspective on this now. 

However, I'm presuming you have also explored the concept of how Organisational protection policies implemented on these technologies may map against the MITRE ATT&CK f/w. Prima facie, it would have to be a sub set of the feature set advertised by a vendor product. How did that experience go, if I may ask?

**Comment by marcusbakker** [comment]
Yes, we have. That part is not, yet, integrated with DeTT&CT (it is on the list for [Future Developments](https://github.com/rabobank-cdc/DeTTECT/wiki/Future-dev)). Besides having preventive or protective measures provided by a vendor as a subset of the features they offer or being their primary functionality. We could of course also have taken for example measures within an OS (like enabling credential guard in Windows).
