### ISSUE TITLE
Cannot connect to MITRE's CTI TAXII server

### ISSUE THREAD

**Issue by microgag** [rabobank-cdc/DeTTECT#114]
Have try running the following to have yaml convert to taxii format, but gotten the following error message.
% python detttect.py generic ds

[!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections

**Comment by Rockso** [comment]
I am getting the same [!] Cannot connect to MITRE's CTI TAXII server: https://cti-taxii.mitre.org/stix/collections

It looks like https://cti-taxii.mitre.org site is down.

**Comment by rubinatorz** [comment]
Hi @Rockso and @microgag 

Please checkout #113.

**Comment by Rockso** [comment]
Thanks!
