### ISSUE TITLE
Latest techniques not appearing in editor

### ISSUE THREAD

**Issue by ktneely** [rabobank-cdc/DeTTECT#118]
It appears that the latest techniques are not appearing in the editor, even when using the latest commits in a docker image.  I will use Additional Container Cluster Roles - T1098.006 as an example.

1. The editor/src/data/techniques.json does include this technique
2. Using the latest Docker Hub build, launch the editor, create a new techniques file, add a technique, search for "T1098" and only up to sub-technique .005 is listed
3. Performing a `git clone` or a `git pull` to get the latest code, followed by `docker build .` to build a new image, then launching the editor likewise only shows up to sub-technique .005 and T1098.006 is missing.

As the sub-technique is in the source files, should this not be available in the editor?

**Comment by rubinatorz** [comment]
hi @ktneely 

Do you still have this problem? I just downloaded the latest docker image and ran the Editor and do see the T1098.006 subtechnique:

<img width="1449" alt="Screenshot 2024-06-05 at 12 08 44" src="https://github.com/rabobank-cdc/DeTTECT/assets/11735227/57685dec-2861-4a73-a1b2-ffe585316721">
