### ISSUE TITLE
Mac zsh

### ISSUE THREAD

**Issue by CarolinaMoonshine** [rabobank-cdc/DeTTECT#119]
When running the dettect.py script in zsh, I'm getting an error that the  "import xslxwriter" module is not found. I ran a git clone of the webpage so all the files are there. I'm running Python3.12

**Comment by rubinatorz** [comment]
Hi @CarolinaMoonshine 

xlsxwriter is one of the python modules that is needed. This, and others, are not installed by default. So you need to install those libraries. That can be done easily by using pip:

```pip install -r requirements.txt```

**Comment by CarolinaMoonshine** [comment]
I'm currently using a MacBook with zsh. Pip is not an option. Trying to install with "brew" doesn't seem to work to well either. Has any testing/development been done to have this work on Mac?

**Comment by rubinatorz** [comment]
Hi @CarolinaMoonshine 

Can you explain why pip is not an option? I mainly develop on macOS and using bash together with python3 and pip. This works perfectly fine. 

Just tried zsh for you and it works too:

```
rubinatorz@MBP DeTTECT % python dettect.py d -ft sample-data/techniques-administration-endpoints.yaml -l --local-stix-path ../cti
File written:   output/detection_example.json
rubinatorz@MBP DeTTECT % echo $0                                                                                                 
zsh
```

I would advise to look into installing python3 and pip before you continue. Running python on macOS is fully supported and installing python packages with pip should be working.

Good luck!

**Comment by CarolinaMoonshine** [comment]
Here are the commands and responses I used:

nick@12345 DeTTECT % brew install python3
Warning: python@3.12 3.12.5 is already installed and up-to-date.
To reinstall 3.12.5, run:
  brew reinstall python@3.12

nick@012345 DeTTECT % brew install pip
Warning: No available formula with the name "pip". Did you mean pipx, pit, pig, pcp, php, pop, pup, sip, vip or zip?
pip is part of the python formula:
  brew install python

nick@12345 DeTTECT % pip install -r requirements.txt
zsh: command not found: pip

**Comment by rubinatorz** [comment]
Great! Closing the issue now.
