### ISSUE TITLE
Questions on Platforms that can be chosen for Internal applications or Databases

### ISSUE THREAD

**Issue by rahulgk-mettle** [rabobank-cdc/DeTTECT#120]
I have been using the framework to map the datasources. Its a fantastic piece of work to come up with such a useful framework. I have a doubt regarding selecting the platforms against the applicable systems. We do have internal applications and databases. However I don't see anything related in the the list of Platforms which I can use for these. I understand these are based on MITRE datasources and platforms. But I wanted to check if there will be some DeTT&CT custom platforms like how the custom datasources are made?

**Comment by rubinatorz** [comment]
Hi @rahulgk-mettle 

Indeed we use the MITRE platforms and we don't have plans for custom DeTT&CT platforms. 

Regards
Ruben
