### ISSUE TITLE
Techniques administration YAML file generation fails if no exceptions are specified

### ISSUE THREAD

**Issue by hRun** [rabobank-cdc/DeTTECT#13]
Using _data-sources-empty.yaml_ as template to document my data sources I noticed _python dettect.py ds -fd sample-data/data-sources-endpoints.yaml -y_ to generate the techniques administration yaml file fails with below error message unless a string value for 
_exceptions:_
  _- technique_id:_
is specified. Specifying a random string will work. Would be nice if either the template mentioned this, had a default value set or the error handling would beadjusted.

Traceback (most recent call last):
  File "dettect.py", line 296, in <module>
    _menu(_init_menu())
  File "dettect.py", line 200, in _menu
    generate_technique_administration_file(file_ds)
  File "/root/Documents/dettect/DeTTECT/data_source_mapping.py", line 512, in generate_technique_administration_file
    techniques_upper = list(map(lambda x: x.upper(), exceptions))
  File "/root/Documents/dettect/DeTTECT/data_source_mapping.py", line 512, in <lambda>
    techniques_upper = list(map(lambda x: x.upper(), exceptions))
AttributeError: 'int' object has no attribute 'upper'

**Comment by marcusbakker** [comment]
Thanks for reporting the bug! We have pushed out a new release ([v1.2.2](https://github.com/rabobank-cdc/DeTTECT/releases/tag/v1.2.2)) that also includes some other minor improvements.
