### ISSUE TITLE
Mapping CVEs to Mitre ATT&CK Framework

### ISSUE THREAD

**Issue by cstayyab** [rabobank-cdc/DeTTECT#14]
Can this tool be used to map CVEs to Mitre ATT&CK Framework? Or any workaround for that in this tool?

**Comment by marcusbakker** [comment]
DeTT&CT has no support for mapping CVEs. You could include information regarding CVEs into the comment field of a detection or misuse the detection or visibility object in its entirety for mapping CVEs. Not sure if that's a workable solution in the scenario you are encountering.

**Comment by ronmag0891** [comment]
Use of CICAT or some form thereof would work for the mapping.
