### ISSUE TITLE
More information on usage of Threat actor group mapping

### ISSUE THREAD

**Issue by mavjs** [rabobank-cdc/DeTTECT#18]
The command usage described in https://github.com/rabobank-cdc/DeTTECT/wiki/Threat-actor-group-mapping does not show how to make use of just the groups mentioned in `groups.yml`

Thus, I would like to add another command example as follows to the wiki:
```
python dettect.py g -g sample-data/groups.yml
```

**Comment by marcusbakker** [comment]
Thank you for the feedback! 

It was already part of the [getting started page](https://github.com/rabobank-cdc/DeTTECT/wiki/Getting-started#threat-actor-group-heat-map). I've now also added it to the 
"threat actor group mapping" page.

Regards,
Marcus
