### ISSUE TITLE
Running dettect.py without a connection to the Internet

### ISSUE THREAD

**Issue by of13tch** [rabobank-cdc/DeTTECT#26]
I am trying to run DeTTECT on a network without external connectivity. I can see that when I generate a datasource layer from the sample data it reaches out to cti-taxii.mitre.org

```
$ python3 dettect.py ds -fd sample-data/data-sources-endpoints.yaml -l
...
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cti-taxii.mitre.org', port=443): Max retries exceeded with url: ...
...
```
Is it possibly to run the module without connecting out, by bringing in the static data?

**Comment by of13tch** [comment]
I was able to generate the cache directory with an Internet connection and then bring that into the closed network. This has allowed me to generate the attack navigation layers as desired.

**Comment by marcusbakker** [comment]
Good to know that you were able to solve it. This is currently also the only way to approach this. One other thing to take into account. You may want to increase the `EXPIRE_TIME` in the file [constants.py](https://github.com/rabobank-cdc/DeTTECT/blob/master/constants.py):

```python
import re

APP_NAME = 'DeTT&CT'
APP_DESC = 'Detect Tactics, Techniques & Combat Threats'
VERSION = '1.3'

EXPIRE_TIME = 60 * 60 * 24
