### ISSUE TITLE
Error while invoking DeTTECT library

### ISSUE THREAD

**Issue by robotbond** [rabobank-cdc/DeTTECT#30]
Hi There, 

I attempted to invoke DeTTECT library but received xlsxwriter module error. Right after that I installed xlsxwriter but the error remain same. What could be wrong ?
admin1@admin1-virtual-machine:~/DeTTECT$ python3 dettect.py 
Traceback (most recent call last):
  File "dettect.py", line 4, in <module>
    from interactive_menu import *
  File "/home/admin1/DeTTECT/interactive_menu.py", line 2, in <module>
    from data_source_mapping import *
  File "/home/admin1/DeTTECT/data_source_mapping.py", line 3, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'

admin1@admin1-virtual-machine:~/DeTTECT$ pip install XlsxWriter
Collecting XlsxWriter
  Using cached https://files.pythonhosted.org/packages/00/1f/2092a81056d36c1b6651a645aa84c1f76bcee03103072d4fe1cb58501d69/XlsxWriter-1.2.8-py2.py3-none-any.whl
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-1.2.8

Regards,
Nitin

**Comment by marcusbakker** [comment]
Hi Nitin,

Could you check if you have installed the Python 3 version of `xlsxwriter` and not Python 2? On some systems the command `pip` executes pip for Python 2 and not 3. Try installing all dependencies by using pip3 and let me know if that solves your problem:
`pip3 install -r requirements.txt`

Regards,
Marcus

**Comment by robotbond** [comment]
Hi Marcus, 

As per your suggestion, I installed all dependencies with pip3 but now getting syntax error 

admin1@admin1-virtual-machine:~/DeTTECT$ python dettect.py 
Traceback (most recent call last):
  File "dettect.py", line 4, in <module>
    from interactive_menu import *
  File "/home/admin1/DeTTECT/interactive_menu.py", line 4, in <module>
    from group_mapping import *
  File "/home/admin1/DeTTECT/group_mapping.py", line 3, in <module>
    from eql_yaml import techniques_search
  File "/home/admin1/DeTTECT/eql_yaml.py", line 360
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

Regards,
Nitin

**Comment by robotbond** [comment]
Hi Marcus, 

Thanks for the support. The issue has been sorted. Thanks !

Regards,
Nitin
