### ISSUE TITLE
Error when generate data based on selected groups.

### ISSUE THREAD

**Issue by aiyede** [rabobank-cdc/DeTTECT#42]
Hi, when I tried to generate data based on selected groups "python dettect.py g -g 'fin7' -g 'cobalt group'", I received error below.

Traceback (most recent call last):
  File "dettect.py", line 365, in <module>
    _menu(_init_menu())
  File "dettect.py", line 290, in _menu
    generate_group_heat_map(args.groups, args.overlay, args.overlay_type, args.platform,
  File "/DeTTECT-master/group_mapping.py", line 572, in generate_group_heat_map
    groups_dict = _get_group_techniques(groups, platform, groups_file_type)
  File "/DeTTECT-master/group_mapping.py", line 211, in _get_group_techniques
    found = _are_groups_found(groups_found, groups)
  File "/DeTTECT-master/group_mapping.py", line 42, in _are_groups_found
    if group_arg in group_aliases_lower or group_arg == get_attack_id(group).lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by rubinatorz** [comment]
hi @aiyede 

I tried to execute the exact same command and I didn't get the error you are getting:

```
$ python dettect.py g -g 'fin7' -g 'cobalt group'
File written:   output/attack_windows_g0080_g0046.json
```

Can you try to remove the cache folder and try it again?

**Comment by aiyede** [comment]
Thanks @rubinatorz, I found the cause was because of some dependencies. After I lined up the dependencies with requirements.txt and cleared up the cache, I was able to generate the file without error. Thank you.

**Comment by rubinatorz** [comment]
@aiyede That's great!
