### ISSUE TITLE
Feature Request - Pages Branch

### ISSUE THREAD

**Issue by clayha** [rabobank-cdc/DeTTECT#43]
It would be handy if there was a **gh-pages branch** for building static sites.

**CyberChef** & **MITRE ATT&CK** provide gh-pages branches for this purpose. This has enabled both to be used within plugins of 3rd party resources, like CALDERA's plugin "CALT&CK": https://github.com/mitre/caltack, as well as by multiple users for ad-hoc work.

**Comment by marcusbakker** [comment]
Would you like to explain that a little more? Not sure if I get it 😅. Or, are you referring to something like this?: https://github.com/rabobank-cdc/dettect-editor

**Comment by clayha** [comment]
Cheers Marcus for the follow-up and sorry for the loose use of words in the requirement.

Correct - I was hoping to there could be a gh-pages branch of the editor. We'd like to host this internally on a downstream repo. The gh-pages branch would allow us to host the site without much fuss or relying on the public version.

**Comment by marcusbakker** [comment]
No worries, thank you for clarifying. I think you can take the following approach:
* Clone the repository at https://github.com/rabobank-cdc/dettect-editor
  * This is automatically kept up-to-date with the latest code for the Editor.
* Place the content into a directory named 'dettect-editor' and place that in the root of your webserver
* You should now be able to access the page from `https://hostname/dettect-editor`

Will the above work for you?

**Comment by clayha** [comment]
Hey sorry, the benefit of a gh-pages branch is that I could host the content using Github Pages vs having a standalone web service running for the editor. Anyone would be able to do the same as well if the forked the repo.

**Comment by marcusbakker** [comment]
Are you referring to the problem as stated on this page? https://gist.github.com/chrisjacob/1086274/6b2e70a2c61e806780d3768e3ef8f0ecced3b6d1
