### ISSUE TITLE
"Getting started" link is broken on the readme file

### ISSUE THREAD

**Issue by fusuyfusuy** [rabobank-cdc/DeTTECT#45]
On the readme file, the URL in "This [page](https://github.com/rabobank-cdc/DeTTECT/blob/master/Getting-started) on the Wiki" is broken. 

I think correct URL would be [this](https://github.com/rabobank-cdc/DeTTECT/wiki/Getting-started).

**Comment by marcusbakker** [comment]
Thanks Yusuf for letting us know!
