### ISSUE TITLE
Data Source creation no longer working

### ISSUE THREAD

**Issue by gunboatdiplomat-ctrl** [rabobank-cdc/DeTTECT#47]
With the latest versions, the data source .yaml files generated no longer include references to individual TTP's, nor will the .json files generated by `dettect.py ds -fd` afterwards.

When trying to convert a data source yaml generated by the Editor to a json, the `needs to be manually updated to have the new ATT&CK v9 data sources/data components as it currently contains ATT&CK v8 data sources.` error is thrown.

**Comment by marcusbakker** [comment]
ATT&CK v9 has revamped the data sources. If you want, you can still use the old data source names with version 1.4.2, and a local copy of ATT&CK v8 provided to DeTT&CT with the argument `--local-stix-path`. However, my advice would be to start using the new data sources to also take advantage of other improvements introduced with ATT&CK v9.

For more info also see the [changelog](https://github.com/rabobank-cdc/DeTTECT/wiki/Changelog#version-143).

**Comment by gunboatdiplomat-ctrl** [comment]
Thank you for the information Marcus - acknowledged. I'm not sure what was going on with my dettect editor but I may have loaded a cached version. I will close this issue.
