### ISSUE TITLE
error converting YAML to JSON

### ISSUE THREAD

**Issue by macarongbadessy** [rabobank-cdc/DeTTECT#48]
Thank you so much for making this tool. However, I am getting an error message when trying to convert YAML to JSON.

I used the command inside the folder where DETTECT is:

python dettect.py ds -fd a.yaml -l

a.yaml is what I named the file

The error message I get is:

[!] Cannot connect to MITRE's CTI TAXII Server

I've used this command last week and it worked great. I guess with the MITRE changes something happened. 

Can you please help?

Thank  you.

**Comment by marcusbakker** [comment]
It seemed like when you ran this command the CTI TAXII server from MITRE was down or you had an internet connection problem: `[!] Cannot connect to MITRE's CTI TAXII Server`

I do not encounter any issues with the command you provided and the TAXII server is up now.

**Comment by macarongbadessy** [comment]
Hmm. I still get that same error. It is possible something may be blocked on our firewall.  Is there a particular URL that needs to be allowed? I tried it again on another laptop and this is the error message I get now.

![image](https://user-images.githubusercontent.com/83777510/117334193-50767a00-ae5f-11eb-8197-1dd89ddafddf.png)

**Comment by macarongbadessy** [comment]
I tried reinstalling DETTECT, but that didn't help

**Comment by marcusbakker** [comment]
URL for the TAXII server: `https://cti-taxii.mitre.org/stix/collections/`

The exception you get in the shared screenshot is a bug: `KeyError: 'PRE'`. I pushed a fix.

**Comment by macarongbadessy** [comment]
It works now. Thank you so much!
