### ISSUE TITLE
Data sources missing

### ISSUE THREAD

**Issue by irivera007** [rabobank-cdc/DeTTECT#53]
HI,

When running in docker or locally, Im unable to see more data sources for instance "AWS CloudTrail logs" from the drop menu:
![image](https://user-images.githubusercontent.com/7444152/121486828-57c10400-c986-11eb-9bd0-3166a74d2e4e.png)

any idea on what am I missing?

**Comment by rubinatorz** [comment]
hi @irivera007 

"AWS CloudTrail logs" is a data source from the previous ATT&CK version (8.0 and before). MITRE restructured and renewed the data sources in version 9.0 and "AWS CloudTrail logs" in not in there.

**Comment by beerMT** [comment]
I found a similar Data Source missing issue when looking at:

- Logon Session Termination
- Scheduled Job Deletion

**Comment by rubinatorz** [comment]
hi @beerMT,

Those 2 data sources are indeed part of ATT&CK v9, but there are no (sub) techniques referencing to this data sources. That's why you don't see those data sources in the Editor. Those data sources would not reflect any visibility on (sub) techniques (yet).

**Comment by beerMT** [comment]
Good catch, thanks for clarification.
