### ISSUE TITLE
Inaccurate threat actor mapping

### ISSUE THREAD

**Issue by moullos** [rabobank-cdc/DeTTECT#56]
Hi and thank you for the amazing project.

I am trying to generate a threat actor mapping for APT29 using the command `python .\dettect.py g -g 'APT29'`. While it completes successfully, it seems that the results are incomplete. For example, subtechnique T1546.003 [should](https://attack.mitre.org/groups/G0016/ )be included in the resulting navigator layer but it is not. 

As github prevents me from uploading the actual json file, I have attaching a screenshot of the navigator:

![image](https://user-images.githubusercontent.com/25383165/143005617-9d35e595-7e21-4220-83da-9bc6d68eed34.png)

For any more information required please let me know.

**Comment by rubinatorz** [comment]
hi @moullos 

Please check your stix2 python library version. I guess it's 3.x. The 3.x version gives some strange results, so you need the stix==2.1.0 version to work with DeTT&CT (as listed in the requirements.txt file).

Regards,
Ruben

**Comment by rubinatorz** [comment]
@moullos You'll probably also need to remove the cache directory after downgrading to stix2==2.1.0, otherwise DeTT&CT will use cached STIX information.
