### ISSUE TITLE
MITRE's CTI TAXII server

### ISSUE THREAD

**Issue by birdmanGW** [rabobank-cdc/DeTTECT#59]
Hello,

While executing dettect.py ds on an input .yaml file, I am receiving the below error:

[!] Cannot connect to MITRE's CTI TAXII server

What may be causing this?

**Comment by rubinatorz** [comment]
Hi @birdmanGW 

I think the CTI TAXII server of MITRE was offline for a moment OR the system where DeTT&CT runs on wasn't able to connect to the internet. Just checked and I'm able to fetch information from the TAXII server right now. So please try again and/or check your internet connection.

Regards,
Ruben

**Comment by bbutz-nydig** [comment]
I am experiencing this.  Can you validate what connection needs to be made?  i.e. domain,url,ip etc... ?

**Comment by rubinatorz** [comment]
hi @bbutz-nydig 

When you are getting the error "[!] Cannot connect to MITRE's CTI TAXII server" it means the TAXII server of MITRE is down for a moment. It tries to connect to cti-taxii.mitre.org over https. When that error is shown, you can wait for the TAXII server to come online again or try the offline mode in DeTT&CT CLI, see the --local-stix-path option.

**Comment by bbutz-nydig** [comment]
Thanks @rubinatorz , It appears that my proxied connection was the culprit.  After running through a system not proxied, I have no issues.  It may be helpful to adjust that error message to indicate what network connection is failing so that a user can request a proxy bypass for it.

**Comment by rubinatorz** [comment]
hi @bbutz-nydig 

Nice suggestion to include the URL in the error message. Just added it: 8465c20fda77cc02cfdcc51d19dc3cd3dc1acc80
