### ISSUE TITLE
Missing Data Sources

### ISSUE THREAD

**Issue by willheineman** [rabobank-cdc/DeTTECT#68]
I am unable to add some data sources through the Editor.

Specific examples:
- https://attack.mitre.org/datasources/DS0026/
- https://attack.mitre.org/datasources/DS0036/
- https://attack.mitre.org/datasources/DS0012/

I am not sure if this is just because DeTTECT does not support the latest content from ATT&CK, or if there are other reasons that the data sources are unavailable.

**Comment by marcusbakker** [comment]
Hi Will,

I can find all of these data sources in the Editor. Did you ensure you included the corresponding platforms for these data sources via a System specification?

<img width="679" alt="image" src="https://user-images.githubusercontent.com/40516252/159575686-7e5fb0d9-9cee-4ca9-b769-fc8e2c3ff913.png">

Regards,
Marcus

**Comment by willheineman** [comment]
You were correct, my system specification was incorrect.
