### ISSUE TITLE
Wiki includes references to (deprecated) interactive mode

### ISSUE THREAD

**Issue by willheineman** [rabobank-cdc/DeTTECT#69]
The Wiki includes help text for how to use the CLI and has references to interactive mode, but per a recent commit this feature was removed:

- Wiki: https://github.com/rabobank-cdc/DeTTECT/wiki/Help-texts
- Commit: https://github.com/rabobank-cdc/DeTTECT/commit/e858d28abfab9e28353261c328783a4a24a6f662

**Comment by marcusbakker** [comment]
Hi Will,

Thanks for letting us know. Something went wrong with a manual update of the Wiki when releasing v1.6.0. Fixed know with a manual run of this Action: [update_wiki_help_texts.yml](https://github.com/rabobank-cdc/DeTTECT/actions/workflows/update_wiki_help_texts.yml)

Regards,
Marcus
