### ISSUE TITLE
Techniques being annotated even when a selected data source not part of the yaml

### ISSUE THREAD

**Issue by roboticsea** [rabobank-cdc/DeTTECT#70]
Hey there!

Thanks so much for this tool!  Really helps me prioritize detections to build.

Maybe I'm doing something wrong, but if I select a data source, for example network connection creation, techniques that do not have that as an available data source are still being annotated by, I believe "applicable to".

If it's a bug in the newest version, I thought I'd submit an issue.  If this is user error, I'm really sorry!

-Rob

**Comment by rubinatorz** [comment]
hi @roboticsea 

We don't quite understand what you mean. Can you please elaborate your issue a bit more and include some screenshots?

**Comment by roboticsea** [comment]
It's probably me doing something wrong, but here's what I did to produce a
yaml for network share access applicable to Windows.  If you look at the
converted json layer in Navigator, it colored the right techniques but all
the other techniques were annotated as well (with Applicable to Windows)

Thanks!!!

**Comment by marcusbakker** [comment]
Could you share some screenshots?

**Comment by roboticsea** [comment]
Sorry, I replied with them on this email.  Let me attach to the issue

**Comment by roboticsea** [comment]
![Screen Shot 2022-04-27 at 11 17 14 AM](https://user-images.githubusercontent.com/39040921/165558816-d319f7b5-9fa9-42c9-83c1-507da6185d37.png)
![Screen Shot 2022-04-27 at 11 10 39 AM](https://user-images.githubusercontent.com/39040921/165558876-57727b4a-d40a-476c-be9b-ee158c255d5f.png)
![Screen Shot 2022-04-27 at 11 10 31 AM](https://user-images.githubusercontent.com/39040921/165558879-cdac15f4-3e56-42c9-b4f3-cb3697ce2a13.png)

**Comment by marcusbakker** [comment]
What you are seeing in the Navigator is correct. For example, the metadata shown for T1200 tells you you're missing a data source to have visibility. Hence the score of 0%.

About the yellow underlying, those can be pretty annoying. We currently have no way of influencing that from the .json layer file. However, one solution is to use a different URL for the ATT&CK Navigator, which removes the yellow underlying for annotated techniques.

https://mitre-attack.github.io/attack-navigator/#comment_underline=false

**Comment by roboticsea** [comment]
Ah, that makes sense.


The reason I was asking is I use these to compare against attack groups
layers to find techniques to build detections for.  When stuff is annotated
like this the comparison layer is skewed.  But, you got me in the right
direction.

Thanks!!

**Comment by marcusbakker** [comment]
Good to hear that. I will close this issue for now.
