### ISSUE TITLE
Editor Issue

### ISSUE THREAD

**Issue by grizzlycode** [rabobank-cdc/DeTTECT#78]
I've installed DeTTECT locally on my machine. When I create 6 systems in "Data Sources" section I can no longer see the "Save button" in the first section. It jumps to the next section automatically. I have to delete the last system to see button again.

**Comment by rubinatorz** [comment]
hi @grizzlycode 

You're completely right. This is annoying. This is because it collapses the upper section automatically on scrolling. We disabled this auto-collapse feature to solve this issue. Please let us know if this solved your issue.

Regards,
Ruben
