### ISSUE TITLE
Cannot create custom group heatmaps

### ISSUE THREAD

**Issue by txapel91** [rabobank-cdc/DeTTECT#86]
When I try to create a heatmap for a few groups I get the error "TypeError: 'NoneType' object is not iterable"
I use the syntax python dettect.py g -g 'group1','group2','group3'

Has there been a change in syntax needed?
This used to work in the past.

Here is the excerpt from the command:

root@c5b999b055c6:/opt/DeTTECT# python dettect.py g -g 'apt10,apt29'
Traceback (most recent call last):
  File "/opt/DeTTECT/dettect.py", line 382, in <module>
    _menu(_init_menu())
  File "/opt/DeTTECT/dettect.py", line 303, in _menu
    generate_group_heat_map(args.groups, args.overlay, args.overlay_type, args.platform,
  File "/opt/DeTTECT/group_mapping.py", line 599, in generate_group_heat_map
    groups_dict = _get_group_techniques(groups, platform, groups_file_type, domain)
  File "/opt/DeTTECT/group_mapping.py", line 208, in _get_group_techniques
    (groups[0] == 'all' or gr['group_id'].lower() in groups or _is_in_group(gr['aliases'], groups) or gr['name'].lower() in groups):
  File "/opt/DeTTECT/group_mapping.py", line 17, in _is_in_group
    json_groups = list(map(lambda x: x.lower(), json_groups))
TypeError: 'NoneType' object is not iterable

**Comment by rubinatorz** [comment]
hi @txapel91 

Thank you for reporting this issue. Your syntax is correct! After investigation I found out that since the latest ATT&CK release something changed in the STIX objects that lead to this error. I just fixed it and you should now be able to run your command.

cheers,
Ruben
