### ISSUE TITLE
Unable to generate groups heatmap

### ISSUE THREAD

**Issue by OpalSec** [rabobank-cdc/DeTTECT#90]
I attempted to generate a groups layer using the sample data - despite using the [exact command suggested](https://github.com/rabobank-cdc/DeTTECT/wiki/Threat-actor-group-mapping#custom-groups), it didn't work:

```
user@ubuntu:/opt/DeTTECT# python dettect.py g -g sample-data/groups.yaml 
Traceback (most recent call last):
  File "dettect.py", line 421, in <module>
    _menu(_init_menu())
  File "dettect.py", line 339, in _menu
    generate_group_heat_map(args.groups, args.campaigns, args.overlay, args.overlay_type, args.platform,
  File "/opt/DeTTECT/group_mapping.py", line 729, in generate_group_heat_map
    groups_dict |= campaigns_dict
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

I'm running Python 3.8.10, which should be supported for this project.

**Comment by rubinatorz** [comment]
hi @OpalSec 

I was using the "|=" operator on line group_mapping.py:729 but this operator is new in Python 3.9. I just changed it to the dict.update(dict) method to support older Python versions. So when you checkout the latest master branch code it should work.

Regards,
Ruben
