### ISSUE TITLE
Excel output for Visibility refers to Detection score, not Visibility score

### ISSUE THREAD

**Issue by tailsec** [rabobank-cdc/DeTTECT#93]
When looking to visualise the Visibility for the Credential Stuffing technique, the yaml file shows there are different scores for Detection (-1) and Visibility (2)

![image](https://user-images.githubusercontent.com/126639182/223611309-00bb9f4a-e501-4307-9f49-dc6258e7ec60.png)

Generating the Excel output gives a value of -1, which appears to stem from the Detection score:

```
(venv) user@ubuntu:/opt/DeTTECT$ python dettect.py v -ft sample-data/techniques-administration-endpoints.yaml -e
File written:   output/techniques.xlsx
```

![image](https://user-images.githubusercontent.com/126639182/223611352-4a28d621-269a-4578-899a-bef642bf9c17.png)

Whereas generating a Navigator Layer provides the correct value of 2:

```
(venv) user@ubuntu:/opt/DeTTECT$ python dettect.py v -ft sample-data/techniques-administration-endpoints.yaml -l
File written:   output/visibility_example_1.json
```

![image](https://user-images.githubusercontent.com/126639182/223611411-cc4455db-6ed4-4217-88d8-d3df105911d8.png)

**Comment by rubinatorz** [comment]
hi @tailsec 

In the excel file there are two worksheets. One for detections, one for visibility. The one in your screenshot is for detections, so please look at the second sheet in that file. There you will find the visibility view.
