### ISSUE TITLE
Windows event log is not available while adding data source option. 

### ISSUE THREAD

**Issue by MohsinSDK** [rabobank-cdc/DeTTECT#99]
Windows event log is not available while adding data source option as shown in the video  https://youtu.be/1zgpTR6D3M8?t=75 s

**Comment by rubinatorz** [comment]
hi @MohsinSDK 

That's because MITRE restructured the data sources since then. In DeTT&CT you'll find the data components as listed per data source on:
https://attack.mitre.org/datasources/
